"""Список частых неправильных глаголов (base, past V2, participle V3, перевод).

Справочник в Грамматике; можно позже подать тренажёром/карточками.
"""

IRREGULAR_VERBS = [
    ("be", "was / were", "been", "быть"),
    ("have", "had", "had", "иметь"),
    ("do", "did", "done", "делать"),
    ("go", "went", "gone", "идти"),
    ("say", "said", "said", "сказать"),
    ("get", "got", "got", "получать"),
    ("make", "made", "made", "делать"),
    ("know", "knew", "known", "знать"),
    ("think", "thought", "thought", "думать"),
    ("take", "took", "taken", "брать"),
    ("see", "saw", "seen", "видеть"),
    ("come", "came", "come", "приходить"),
    ("give", "gave", "given", "давать"),
    ("find", "found", "found", "находить"),
    ("tell", "told", "told", "рассказывать"),
    ("become", "became", "become", "становиться"),
    ("leave", "left", "left", "уходить, оставлять"),
    ("feel", "felt", "felt", "чувствовать"),
    ("put", "put", "put", "класть"),
    ("bring", "brought", "brought", "приносить"),
    ("begin", "began", "begun", "начинать"),
    ("keep", "kept", "kept", "хранить"),
    ("hold", "held", "held", "держать"),
    ("write", "wrote", "written", "писать"),
    ("stand", "stood", "stood", "стоять"),
    ("hear", "heard", "heard", "слышать"),
    ("let", "let", "let", "позволять"),
    ("mean", "meant", "meant", "значить"),
    ("meet", "met", "met", "встречать"),
    ("run", "ran", "run", "бежать"),
    ("pay", "paid", "paid", "платить"),
    ("sit", "sat", "sat", "сидеть"),
    ("speak", "spoke", "spoken", "говорить"),
    ("lead", "led", "led", "вести"),
    ("read", "read", "read", "читать"),
    ("grow", "grew", "grown", "расти"),
    ("lose", "lost", "lost", "терять"),
    ("fall", "fell", "fallen", "падать"),
    ("send", "sent", "sent", "отправлять"),
    ("build", "built", "built", "строить"),
    ("understand", "understood", "understood", "понимать"),
    ("draw", "drew", "drawn", "рисовать"),
    ("break", "broke", "broken", "ломать"),
    ("spend", "spent", "spent", "тратить"),
    ("cut", "cut", "cut", "резать"),
    ("rise", "rose", "risen", "подниматься"),
    ("drive", "drove", "driven", "водить"),
    ("buy", "bought", "bought", "покупать"),
    ("wear", "wore", "worn", "носить (одежду)"),
    ("choose", "chose", "chosen", "выбирать"),
    ("eat", "ate", "eaten", "есть"),
    ("drink", "drank", "drunk", "пить"),
    ("swim", "swam", "swum", "плавать"),
    ("sing", "sang", "sung", "петь"),
    ("fly", "flew", "flown", "летать"),
    ("sleep", "slept", "slept", "спать"),
    ("teach", "taught", "taught", "учить, обучать"),
    ("catch", "caught", "caught", "ловить"),
    ("throw", "threw", "thrown", "бросать"),
    ("win", "won", "won", "выигрывать"),
]
